# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mysite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
